CIRCT: lib/Dialect/FIRRTL/FIRRTLOps.cpp File Reference
FIRRTLOps.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "circt/Dialect/FIRRTL/FIRRTL.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
template<typename T >
static SmallVector< T > removeElementsAtIndices (ArrayRef< T > input, ArrayRef< unsigned > indicesToDrop)
Remove elements at the specified indices from the input array, returning the elements not mentioned.
void getAsmBlockArgumentNamesImpl (Operation *op, mlir::Region &region, OpAsmSetValueNameFn setNameFn)
Get a special name to use when printing the entry block arguments of the region contained by an operation in this dialect.
static InstanceOp getInstance (FModuleOp mod, StringAttr name)
static InstanceOp getInstance (mlir::SymbolTable &symtbl, hw::InnerRefAttr name)
static bool hasPortNamed (FModuleLike op, StringAttr name)
static bool hasValNamed (FModuleLike op, StringAttr name)
static ParseResult parseCircuitOpAttrs (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printCircuitOpAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static SmallVector< PortInfo > getPorts (FModuleLike module)
This function can extract information about ports from a module and an extmodule or genmodule.
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, ArrayRef< PortInfo > ports, ArrayAttr annotations)
static bool printModulePorts (OpAsmPrinter &p, Block *block, ArrayRef< Direction > portDirections, ArrayRef< Attribute > portNames, ArrayRef< Attribute > portTypes, ArrayRef< Attribute > portAnnotations, ArrayRef< Attribute > portSyms)
Print a list of module ports in the following form: in x: !firrtl.uint<1> [{class = "DontTouch}], out "_port": !firrtl.uint<2>
static ParseResult parseModulePorts (OpAsmParser &parser, bool hasSSAIdentifiers, SmallVectorImpl< OpAsmParser::Argument > &entryArgs, SmallVectorImpl< Direction > &portDirections, SmallVectorImpl< Attribute > &portNames, SmallVectorImpl< Attribute > &portTypes, SmallVectorImpl< Attribute > &portAnnotations, SmallVectorImpl< Attribute > &portSyms)
Parse a list of module ports.
static void printParameterList (ArrayAttr parameters, OpAsmPrinter &p)
Print a paramter list for a module or instance.
static void printFModuleLikeOp (OpAsmPrinter &p, FModuleLike op)
static ParseResult parseOptionalParameters (OpAsmParser &parser, SmallVectorImpl< Attribute > &parameters)
Parse an parameter list if present.
static ParseResult parseFModuleLikeOp (OpAsmParser &parser, OperationState &result, bool hasSSAIdentifiers)
static MemOp::PortKind getMemPortKindFromType (FIRRTLType type)
Return the kind of port this is given the port type from a 'mem' decl.
static LogicalResult checkConnectFlow (Operation *connect)
static Attribute getAttr (ArrayRef< NamedAttribute > attrs, StringRef name)
Get an attribute by name from a list of named attributes.
static bool isSameIntTypeKind (Type lhs, Type rhs, int32_t &lhsWidth, int32_t &rhsWidth, Optional< Location > loc)
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
static FIRRTLType inferMuxReturnType (FIRRTLType high, FIRRTLType low, Optional< Location > loc)
Infer the result type for a multiplexer given its two operand types, which may be aggregates.
static ParseResult parseElideAnnotations (OpAsmParser &parser, NamedAttrList &resultAttrs)
Parse an optional attribute dictionary, adding an empty 'annotations' attribute if not specified.
static void printElideAnnotations (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseElidePortAnnotations (OpAsmParser &parser, NamedAttrList &resultAttrs)
Parse an optional attribute dictionary, adding empty 'annotations' and 'portAnnotations' attributes if not specified.
static void printElidePortAnnotations (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseImplicitSSAName (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printImplicitSSAName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseMemOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printMemOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
static ParseResult parseElideEmptyName (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printElideEmptyName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parsePrintfAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printPrintfAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static ParseResult parseStopAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printStopAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static ParseResult parseVerifAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printVerifAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static void genericAsmResultNames (Operation *op, OpAsmSetValueNameFn setNameFn)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 3791 of file FIRRTLOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, ArrayRef< PortInfo > ports, ArrayAttr annotations) static
Definition at line 674 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), and circt::firrtl::direction::packAttribute().
checkConnectFlow()
static LogicalResult checkConnectFlow (Operation * connect) static
Definition at line 2043 of file FIRRTLOps.cpp.
References circt.support::connect(), circt::firrtl::foldFlow(), and circt::firrtl::getDeclarationKind().
genericAsmResultNames()
static void genericAsmResultNames (Operation * op, OpAsmSetValueNameFn setNameFn) static
Definition at line 3647 of file FIRRTLOps.cpp.
getAsmBlockArgumentNamesImpl()
void getAsmBlockArgumentNamesImpl (Operation * op, mlir::Region & region, OpAsmSetValueNameFn setNameFn)
Get a special name to use when printing the entry block arguments of the region contained by an operation in this dialect.
Definition at line 188 of file FIRRTLOps.cpp.
getAttr()
static Attribute getAttr (ArrayRef< NamedAttribute > attrs, StringRef name) static
Get an attribute by name from a list of named attributes.
Same as above, but casts the attribute to a specific type.
Aborts if the attribute does not exist.
Definition at line 2164 of file FIRRTLOps.cpp.
Referenced by Deduper::makeAnnotationNonLocal().
getInstance() [1/2]
static InstanceOp getInstance (FModuleOp mod, StringAttr name) static
Definition at line 208 of file FIRRTLOps.cpp.
Referenced by getInstance().
getInstance() [2/2]
static InstanceOp getInstance (mlir::SymbolTable & symtbl, hw::InnerRefAttr name) static
Definition at line 215 of file FIRRTLOps.cpp.
References getInstance().
getMemPortKindFromType()
static MemOp::PortKind getMemPortKindFromType (FIRRTLType type) static
Return the kind of port this is given the port type from a 'mem' decl.
Definition at line 1833 of file FIRRTLOps.cpp.
getPorts()
static SmallVector<PortInfo> getPorts (FModuleLike module) static
This function can extract information about ports from a module and an extmodule or genmodule.
Definition at line 447 of file FIRRTLOps.cpp.
References circt::firrtl::AnnotationSet::forPort().
hasPortNamed()
static bool hasPortNamed (FModuleLike op, StringAttr name) static
Definition at line 223 of file FIRRTLOps.cpp.
hasValNamed()
static bool hasValNamed (FModuleLike op, StringAttr name) static
Definition at line 229 of file FIRRTLOps.cpp.
inferMuxReturnType()
static FIRRTLType inferMuxReturnType (FIRRTLType high, FIRRTLType low, Optional< Location > loc) static
Infer the result type for a multiplexer given its two operand types, which may be aggregates.
This essentially performs a pairwise comparison of fields and elements, as follows:
Identical operands inferred to their common type
Integer operands inferred to the larger one if both have a known width, a widthless integer otherwise.
Vectors inferred based on the element type.
Bundles inferred in a pairwise fashion based on the field types.
Definition at line 2944 of file FIRRTLOps.cpp.
References circt::calyx::direction::get().
isSameIntTypeKind()
static bool isSameIntTypeKind (Type lhs, Type rhs, int32_t & lhsWidth, int32_t & rhsWidth, Optional< Location > loc) static
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
If unknown, return -1 for the widths.
On failure, this reports and error and returns false. This function should not be used if you don't want an error reported.
Definition at line 2550 of file FIRRTLOps.cpp.
parseCircuitOpAttrs()
static ParseResult parseCircuitOpAttrs (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 267 of file FIRRTLOps.cpp.
parseElideAnnotations()
static ParseResult parseElideAnnotations (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Parse an optional attribute dictionary, adding an empty 'annotations' attribute if not specified.
Definition at line 3235 of file FIRRTLOps.cpp.
Referenced by parseElidePortAnnotations(), and parseImplicitSSAName().
parseElideEmptyName()
static ParseResult parseElideEmptyName (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 3347 of file FIRRTLOps.cpp.
Referenced by parsePrintfAttrs(), parseStopAttrs(), and parseVerifAttrs().
parseElidePortAnnotations()
static ParseResult parseElidePortAnnotations (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Parse an optional attribute dictionary, adding empty 'annotations' and 'portAnnotations' attributes if not specified.
Definition at line 3257 of file FIRRTLOps.cpp.
References parseElideAnnotations().
Referenced by parseMemOp().
parseFModuleLikeOp()
static ParseResult parseFModuleLikeOp (OpAsmParser & parser, OperationState & result, bool hasSSAIdentifiers) static
Definition at line 1040 of file FIRRTLOps.cpp.
parseImplicitSSAName()
static ParseResult parseImplicitSSAName (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 3286 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), isdigit, and parseElideAnnotations().
parseMemOp()
static ParseResult parseMemOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 3333 of file FIRRTLOps.cpp.
References parseElidePortAnnotations().
parseModulePorts()
static ParseResult parseModulePorts (OpAsmParser & parser, bool hasSSAIdentifiers, SmallVectorImpl< OpAsmParser::Argument > & entryArgs, SmallVectorImpl< Direction > & portDirections, SmallVectorImpl< Attribute > & portNames, SmallVectorImpl< Attribute > & portTypes, SmallVectorImpl< Attribute > & portAnnotations, SmallVectorImpl< Attribute > & portSyms) static
Parse a list of module ports.
If port names are SSA identifiers, then this will populate entryArgs.
Definition at line 854 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::firrtl::In, isdigit, and circt::firrtl::Out.
parseOptionalParameters()
static ParseResult parseOptionalParameters (OpAsmParser & parser, SmallVectorImpl< Attribute > & parameters) static
Parse an parameter list if present.
module-parameter-list ::= < parameter-decl (, parameter-decl)* > parameter-decl ::= identifier : type parameter-decl ::= identifier : type = attribute
Definition at line 1014 of file FIRRTLOps.cpp.
parsePrintfAttrs()
static ParseResult parsePrintfAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 3367 of file FIRRTLOps.cpp.
References parseElideEmptyName().
parseStopAttrs()
static ParseResult parseStopAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 3377 of file FIRRTLOps.cpp.
References parseElideEmptyName().
parseVerifAttrs()
static ParseResult parseVerifAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 3386 of file FIRRTLOps.cpp.
References parseElideEmptyName().
printCircuitOpAttrs()
static void printCircuitOpAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 276 of file FIRRTLOps.cpp.
printElideAnnotations()
static void printElideAnnotations (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 3244 of file FIRRTLOps.cpp.
printElideEmptyName()
static void printElideEmptyName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 3356 of file FIRRTLOps.cpp.
Referenced by printPrintfAttrs(), printStopAttrs(), and printVerifAttrs().
printElidePortAnnotations()
static void printElidePortAnnotations (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 3271 of file FIRRTLOps.cpp.
Referenced by printMemOp().
printFModuleLikeOp()
static void printFModuleLikeOp (OpAsmPrinter & p, FModuleLike op) static
Definition at line 948 of file FIRRTLOps.cpp.
printImplicitSSAName()
static void printImplicitSSAName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 3306 of file FIRRTLOps.cpp.
printMemOp()
static void printMemOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
Definition at line 3338 of file FIRRTLOps.cpp.
References printElidePortAnnotations().
printModulePorts()
static bool printModulePorts (OpAsmPrinter & p, Block * block, ArrayRef< Direction > portDirections, ArrayRef< Attribute > portNames, ArrayRef< Attribute > portTypes, ArrayRef< Attribute > portAnnotations, ArrayRef< Attribute > portSyms) static
Print a list of module ports in the following form: in x: !firrtl.uint<1> [{class = "DontTouch}], out "_port": !firrtl.uint<2>
When there is no block specified, the port names print as MLIR identifiers, wrapping in quotes if not legal to print as-is. When there is no block specified, this function always return false, indicating that there was no issue printing port names.
If there is a block specified, then port names will be printed as SSA values. If there is a reason the printed SSA values can't match the true port name, then this function will return true. When this happens, the caller should print the port names as a part of the attr-dict.
Definition at line 786 of file FIRRTLOps.cpp.
printParameterList()
static void printParameterList (ArrayAttr parameters, OpAsmPrinter & p) static
Print a paramter list for a module or instance.
Definition at line 932 of file FIRRTLOps.cpp.
printPrintfAttrs()
static void printPrintfAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 3372 of file FIRRTLOps.cpp.
References printElideEmptyName().
printStopAttrs()
static void printStopAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 3381 of file FIRRTLOps.cpp.
References printElideEmptyName().
printVerifAttrs()
static void printVerifAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 3390 of file FIRRTLOps.cpp.
References printElideEmptyName().
removeElementsAtIndices()
template<typename T > static SmallVector<T> removeElementsAtIndices (ArrayRef< T > input, ArrayRef< unsigned > indicesToDrop) static
Remove elements at the specified indices from the input array, returning the elements not mentioned.
The indices array is expected to be sorted and unique.
Definition at line 49 of file FIRRTLOps.cpp.