CIRCT: lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp File Reference
FIRRTLAnnotationHelper.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
static bool hasName (StringRef name, Operation *op)
Abstraction over namable things. Do they have names?
static AnnoTarget findNamedThing (StringRef name, Operation *op)
Find a matching name in an operation (usually FModuleOp).
static LogicalResult updateExpandedPort (StringRef field, AnnoTarget &ref)
static FailureOr< unsigned > findBundleElement (Operation *op, Type type, StringRef field)
Try to resolve an non-array aggregate name from a target given the type and operation of the resolved target.
static FailureOr< unsigned > findVectorElement (Operation *op, Type type, StringRef indexStr)
Try to resolve an array index from a target given the type of the resolved target.
static FailureOr< unsigned > findFieldID (AnnoTarget &ref, ArrayRef< TargetToken > tokens)
Function Documentation
findBundleElement()
static FailureOr<unsigned> findBundleElement (Operation * op, Type type, StringRef field) static
Try to resolve an non-array aggregate name from a target given the type and operation of the resolved target.
This needs to deal with places where we represent bundle returns as split into constituent parts.
Definition at line 73 of file FIRRTLAnnotationHelper.cpp.
Referenced by findFieldID().
findFieldID()
static FailureOr<unsigned> findFieldID (AnnoTarget & ref, ArrayRef< TargetToken > tokens) static
Definition at line 108 of file FIRRTLAnnotationHelper.cpp.
References findBundleElement(), findVectorElement(), and updateExpandedPort().
Referenced by circt::firrtl::resolveEntities().
findNamedThing()
static AnnoTarget findNamedThing (StringRef name, Operation * op) static
Find a matching name in an operation (usually FModuleOp).
This walk could be cached in the future. This finds a port or operation for a given name.
Definition at line 34 of file FIRRTLAnnotationHelper.cpp.
References hasName().
Referenced by circt::firrtl::resolveEntities().
findVectorElement()
static FailureOr<unsigned> findVectorElement (Operation * op, Type type, StringRef indexStr) static
Try to resolve an array index from a target given the type of the resolved target.
Definition at line 92 of file FIRRTLAnnotationHelper.cpp.
Referenced by findFieldID().
hasName()
static bool hasName (StringRef name, Operation * op) static
Abstraction over namable things. Do they have names?
Definition at line 24 of file FIRRTLAnnotationHelper.cpp.
Referenced by findNamedThing().
updateExpandedPort()
static LogicalResult updateExpandedPort (StringRef field, AnnoTarget & ref) static
Definition at line 59 of file FIRRTLAnnotationHelper.cpp.
Referenced by findFieldID().