CIRCT: lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp File Reference
IMConstProp.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/APInt.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/TinyPtrVector.h"
Functions
static bool isWireOrReg (Operation *op)
Return true if this is a wire or register.
static bool isAggregate (Operation *op)
Return true if this is an aggregate indexer.
static bool isDeletableWireOrReg (Operation *op)
Return true if this is a wire or register we're allowed to delete.
Function Documentation
isAggregate()
static bool isAggregate (Operation * op) static
Return true if this is an aggregate indexer.
Definition at line 28 of file IMConstProp.cpp.
isDeletableWireOrReg()
static bool isDeletableWireOrReg (Operation * op) static
Return true if this is a wire or register we're allowed to delete.
Definition at line 33 of file IMConstProp.cpp.
References circt::firrtl::hasDontTouch(), circt::firrtl::isUselessName(), and isWireOrReg().
isWireOrReg()
static bool isWireOrReg (Operation * op) static
Return true if this is a wire or register.
Definition at line 23 of file IMConstProp.cpp.
Referenced by isDeletableWireOrReg().