CIRCT: lib/Conversion/ExportVerilog/PrepareForEmission.cpp File Reference
PrepareForEmission.cpp File Reference
#include "ExportVerilogInternals.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Support/LoweringOptions.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
static bool shouldSpillWire (Operation &op, const LoweringOptions &options)
static void lowerBoundInstance (InstanceOp op)
static void lowerInstanceResults (InstanceOp op)
static void lowerAlwaysInlineOperation (Operation *op)
static Value lowerFullyAssociativeOp (Operation &op, OperandRange operands, SmallVector< Operation * > &newOps)
Lower a variadic fully-associative operation into an expression tree.
static void lowerUsersToTemporaryWire (Operation &op)
When we find that an operation is used before it is defined in a graph region, we emit an explicit wire to resolve the issue.
static Operation * rewriteAddWithNegativeConstant (comb::AddOp add, hw::ConstantOp rhsCst)
Transform "a + -cst" ==> "a - cst" for prettier output.
static Operation * findParentInNonProceduralRegion (Operation *op)
Given an operation in a procedural region, scan up the region tree to find the first operation in a graph region (typically an always or initial op).
static bool rewriteSideEffectingExpr (Operation *op)
This function is invoked on side effecting Verilog expressions when we're in 'disallowLocalVariables' mode for old Verilog clients.
static bool hoistNonSideEffectExpr (Operation *op)
This function is called for non-side-effecting Verilog expressions when we're in 'disallowLocalVariables' mode for old Verilog clients.
static bool isMovableDeclaration (Operation *op)
Check whether an op is a declaration that can be moved.
static void reuseExistingInOut (Operation *op)
If exactly one use of this op is an assign, replace the other uses with a read from the assigned wire or reg.
Function Documentation
findParentInNonProceduralRegion()
static Operation* findParentInNonProceduralRegion (Operation * op) static
Given an operation in a procedural region, scan up the region tree to find the first operation in a graph region (typically an always or initial op).
By looking for a graph region, we will stop at graph-region #ifdef's that may enclose this operation.
Definition at line 287 of file PrepareForEmission.cpp.
Referenced by hoistNonSideEffectExpr(), and rewriteSideEffectingExpr().
hoistNonSideEffectExpr()
static bool hoistNonSideEffectExpr (Operation * op) static
This function is called for non-side-effecting Verilog expressions when we're in 'disallowLocalVariables' mode for old Verilog clients.
It hoists non-constant expressions out to the top level so they don't turn into local variable declarations.
Definition at line 338 of file PrepareForEmission.cpp.
References findParentInNonProceduralRegion(), and circt::ExportVerilog::isExpressionAlwaysInline().
Referenced by circt::ExportVerilog::prepareHWModule().
isMovableDeclaration()
static bool isMovableDeclaration (Operation * op) static
Check whether an op is a declaration that can be moved.
Definition at line 385 of file PrepareForEmission.cpp.
Referenced by circt::ExportVerilog::prepareHWModule().
lowerAlwaysInlineOperation()
static void lowerAlwaysInlineOperation (Operation * op) static
Definition at line 159 of file PrepareForEmission.cpp.
References circt::ExportVerilog::isExpressionAlwaysInline().
Referenced by circt::ExportVerilog::prepareHWModule().
lowerBoundInstance()
static void lowerBoundInstance (InstanceOp op) static
Definition at line 82 of file PrepareForEmission.cpp.
References circt.support::connect(), getModulePortInfo(), and circt::ExportVerilog::isSimpleReadOrPort().
Referenced by circt::ExportVerilog::prepareHWModule().
lowerFullyAssociativeOp()
static Value lowerFullyAssociativeOp (Operation & op, OperandRange operands, SmallVector< Operation * > & newOps) static
Lower a variadic fully-associative operation into an expression tree.
This enables long-line splitting to work with them.
Definition at line 212 of file PrepareForEmission.cpp.
Referenced by circt::ExportVerilog::prepareHWModule().
lowerInstanceResults()
static void lowerInstanceResults (InstanceOp op) static
Definition at line 115 of file PrepareForEmission.cpp.
References circt.support::connect(), and getModulePortInfo().
Referenced by circt::ExportVerilog::prepareHWModule().
lowerUsersToTemporaryWire()
static void lowerUsersToTemporaryWire (Operation & op) static
When we find that an operation is used before it is defined in a graph region, we emit an explicit wire to resolve the issue.
Definition at line 247 of file PrepareForEmission.cpp.
References circt.support::connect().
Referenced by circt::ExportVerilog::prepareHWModule().
reuseExistingInOut()
static void reuseExistingInOut (Operation * op) static
If exactly one use of this op is an assign, replace the other uses with a read from the assigned wire or reg.
This assumes the preconditions for doing so are met: op must be an expression in a non-procedural region.
Definition at line 394 of file PrepareForEmission.cpp.
Referenced by circt::ExportVerilog::prepareHWModule().
rewriteAddWithNegativeConstant()
static Operation* rewriteAddWithNegativeConstant (comb::AddOp add, hw::ConstantOp rhsCst) static
Transform "a + -cst" ==> "a - cst" for prettier output.
This returns the first operation emitted.
Definition at line 268 of file PrepareForEmission.cpp.
Referenced by circt::ExportVerilog::prepareHWModule().
rewriteSideEffectingExpr()
static bool rewriteSideEffectingExpr (Operation * op) static
This function is invoked on side effecting Verilog expressions when we're in 'disallowLocalVariables' mode for old Verilog clients.
This ensures that any side effecting expressions are only used by a single BPAssign to a sv.reg operation. This ensures that the verilog emitter doesn't have to worry about spilling them.
This returns true if the op was rewritten, false otherwise.
Definition at line 303 of file PrepareForEmission.cpp.
References findParentInNonProceduralRegion(), and seq::reg().
Referenced by circt::ExportVerilog::prepareHWModule().
shouldSpillWire()
static bool shouldSpillWire (Operation & op, const LoweringOptions & options) static
Definition at line 50 of file PrepareForEmission.cpp.
References circt::ExportVerilog::isVerilogExpression(), circt::LoweringOptions::maximumNumberOfTermsInConcat, and circt::LoweringOptions::maximumNumberOfTermsPerExpression.
Referenced by circt::ExportVerilog::prepareHWModule().