CIRCT: circt::sv::CasePattern Struct Reference
circt::sv::CasePattern Struct Reference
#include <SVOps.h>
Classes
struct DefaultPatternTag
Public Member Functions
size_t getWidth () const
CasePatternBit getBit (size_t bitNumber) const
Return the specified bit, bit 0 is the least significant bit.
bool isDefault () const
Return true if this pattern always matches.
bool hasX () const
Return true if this pattern has an X.
bool hasZ () const
Return true if this pattern has an Z.
CasePattern (ArrayRef< CasePatternBit > bits, MLIRContext *context)
Get a CasePattern from a specified list of CasePatternBit.
CasePattern (const APInt &value, MLIRContext *context)
Get a CasePattern for the specified constant value.
CasePattern (IntegerAttr attr)
Get a CasePattern with a correctly encoded attribute.
CasePattern (size_t width, DefaultPatternTag, MLIRContext *context)
Get a CasePattern of a default for the specified width.
Public Attributes
IntegerAttr attr
Detailed Description
Definition at line 47 of file SVOps.h.
Constructor & Destructor Documentation
CasePattern() [1/4]
CasePattern::CasePattern (ArrayRef< CasePatternBit > bits, MLIRContext * context)
Get a CasePattern from a specified list of CasePatternBit.
Bits are specified in most least significant order - element zero is the least significant bit.
Definition at line 651 of file SVOps.cpp.
References attr, bits(), and circt::calyx::direction::get().
CasePattern() [2/4]
CasePattern::CasePattern (const APInt & value, MLIRContext * context)
Get a CasePattern for the specified constant value.
Definition at line 638 of file SVOps.cpp.
CasePattern() [3/4]
circt::sv::CasePattern::CasePattern (IntegerAttr attr) inline
Get a CasePattern with a correctly encoded attribute.
Definition at line 76 of file SVOps.h.
CasePattern() [4/4]
CasePattern::CasePattern (size_t width, DefaultPatternTag , MLIRContext * context)
Get a CasePattern of a default for the specified width.
Definition at line 641 of file SVOps.cpp.
References attr, and circt::calyx::direction::get().
Member Function Documentation
getBit()
auto CasePattern::getBit (size_t bitNumber) const
Return the specified bit, bit 0 is the least significant bit.
Definition at line 603 of file SVOps.cpp.
Referenced by hasX(), and hasZ().
getWidth()
size_t circt::sv::CasePattern::getWidth () const inline
Definition at line 53 of file SVOps.h.
References attr.
Referenced by hasX(), and hasZ().
hasX()
bool CasePattern::hasX () const
Return true if this pattern has an X.
Definition at line 612 of file SVOps.cpp.
References circt::sv::AnyX, getBit(), and getWidth().
hasZ()
bool CasePattern::hasZ () const
Return true if this pattern has an Z.
Definition at line 619 of file SVOps.cpp.
References circt::sv::AnyZ, getBit(), and getWidth().
isDefault()
bool CasePattern::isDefault () const
Return true if this pattern always matches.
Definition at line 608 of file SVOps.cpp.
References attr.
Member Data Documentation
attr
IntegerAttr circt::sv::CasePattern::attr
Definition at line 48 of file SVOps.h.
Referenced by CasePattern(), getWidth(), and isDefault().
The documentation for this struct was generated from the following files:
include/circt/Dialect/SV/SVOps.h
lib/Dialect/SV/SVOps.cpp